graphics.off()
sAleatoria = rnorm(200,0,0.1)
plot.ts(sAleatoria,xlab='tempo',ylab='observacoes')
acf(sAleatoria,main='ACF',xlab='defasagem',ylab='autocorrelacoes')
pacf(sAleatoria,main='PACF',xlab='defasagem',ylab='autocorrelacoes')
